name: Send notification on release created

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'version to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pull-image
        run: |
          docker pull public.ecr.aws/firecracker/fcuvm:v71

      - name: build
        run: |
          export VERSION=${{ github.event.inputs.release }}
          ./tools/devtool build --release
