name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pull-image
        run: |
          docker pull public.ecr.aws/firecracker/fcuvm:v71

      - name: build
        run: |
          ./tools/devtool build --release

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/cargo_target/x86_64-unknown-linux-musl/release
